FloatLayout:
    LiveFeed:
        id: live_feed_widget
        size_hint: 0.2, 0.3
        pos_hint: {"right": 1, "top": 1}

    BoxLayout:
        orientation: 'vertical'
        size_hint: 1, 1

        Label:
            text: f"[b]Welcome to the Language Learner, {app.user_name}[/b]"
            size_hint: 1, 0.1
            markup: True
        ScrollView:
            size_hint: 1, 0.3
            do_scroll_y: True

            Label:
                text: app.system_feedback
                markup: True

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, 0.45

            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.5, 1
                padding: 20     # px

                Label:
                    text: f"[b]Your sentence[/b]"
                    markup: True
                Label:
                    text: f"{app.sentence}"
                    text_size: self.width, None
                    halign: 'center'
                    markup: True

            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.5, 1
                padding: 20

                Label:
                    text: f"[b]Evaluation[/b]"
                    markup: True
                Label:
                    text: app.evaluation
                    text_size: self.width, None
                    halign: 'center'
                    markup: True

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, 0.15

            Button:
                text: "Quit program"
                on_press: app.on_quit()

            Button:
                text: app.b2_text
                on_press: app.on_b2_press()
